# Generated by Django 5.0.7 on 2024-09-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
