# Generated by Django 5.0.7 on 2024-09-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_proyecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
