# Generated by Django 5.0.7 on 2024-09-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_delete_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rational', models.IntegerField(default=0)),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(auto_now=True)),
                ('area', models.TextField(max_length=250)),
                ('coordinador', models.IntegerField(default=0)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
    ]
