# Generated by Django 5.0.7 on 2024-09-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formulario', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=250)),
                ('programador', models.IntegerField(default=0)),
                ('coordinador', models.IntegerField(default=0)),
            ],
        ),
    ]
