# Generated by Django 5.0.7 on 2024-09-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.IntegerField(default=0)),
                ('usuario', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=250)),
                ('tipo_permisos', models.IntegerField(default=0)),
                ('usuario', models.CharField(max_length=200)),
                ('cantidad_prog', models.IntegerField(default=0)),
                ('cantidad_proy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=300)),
                ('descripcion', models.TextField(max_length=200)),
                ('fecha_traslado', models.DateTimeField(auto_now_add=True)),
                ('programador', models.IntegerField(default=0)),
                ('coordinador', models.IntegerField(default=0)),
                ('bitacora', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('corporativo', models.IntegerField(default=0)),
                ('antiguedad', models.IntegerField(default=0)),
                ('usuario_tso', models.CharField(max_length=10)),
                ('firma', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
