# Generated by Django 5.0.7 on 2024-10-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_etapa_role_traslado_usuario_delete_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('etapa_actual', models.IntegerField(default=0)),
                ('etapa_traslado', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.IntegerField(default=0)),
                ('ambiente', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Traslado',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='coordinador',
            new_name='proyecto',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_inicio',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre_proyecto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='numero_rational',
            new_name='rational',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nombre_formulario',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='programador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='firma',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_tso',
            field=models.CharField(max_length=4),
        ),
    ]
