# Generated by Django 5.0.7 on 2024-10-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_alter_usuario_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='antiguedad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='corporativo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='firma',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(),
        ),
    ]
