# Generated by Django 5.0.7 on 2024-10-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_region_cics_tipo_programa_version_cobol_programa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='formulario',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
