# Generated by Django 5.0.7 on 2024-10-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_tipo_formulario_formulario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='corporativo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='evento',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='usuario',
            field=models.IntegerField(default=0),
        ),
    ]
