# Generated by Django 5.0.7 on 2024-10-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_bitacora_corporativo_bitacora_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='formulario',
        ),
        migrations.AddField(
            model_name='programa',
            name='formulario_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspace',
            name='formulario_id',
            field=models.IntegerField(default=0),
        ),
    ]
