# Generated by Django 5.0.7 on 2024-11-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_remove_programa_formulario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('programa', models.IntegerField(default=0)),
            ],
        ),
    ]
